### PR TITLE
Bugfix for maize from Greg McLean.

### PR DESCRIPTION
**Pull request by hol430**
Working on #1667

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by peter-devoil** [comment]
retest this please jenkins

**Comment by hol430** [comment]
This is probably still shot - there's a problem with the ftp server on Bob which I need to get back to. Can't upload the self-extracting binaries archive.

**Comment by hol430** [comment]
retest this please jenkins

**Pull request closed without merging**
