### PR TITLE
Changed BuildAll.xml to use git clean rather than heavy-duty C# script.

### PR DESCRIPTION
**Pull request by hol430**
Working on #1747

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
The apsim classic builds have the same problem as apsim next gen and will continue to fail until we can obtain a new code signing certificate.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@hol353 this is green (finally!) - it should get the other builds going if you merge it. Note that I had to disable code signing for now. Seems like it may be some time before we're able to get that working again?

**Comment by peter-devoil** [comment]
The lack of signed installer may stop installation on "corporate" rollouts. I'll see if I can find a guinea pig..

**Pull request merged**
