### PR TITLE
Added AI acknowledgement message to splash screen

### PR DESCRIPTION
**Pull request by peter-devoil**
Resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1745

### CODE REVIEW

**Comment by peter-devoil** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@hol430 Can you have a look at why this is failing?

**Comment by hol430** [comment]
Says the pagefile is too small. I've just restarted Muck. Will re-run the job in a minute after he's rebooted.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by peter-devoil** [comment]
retest this please jenkins

**Comment by hol430** [comment]
I think there's still a problem with the install scripts which I haven't looked into yet. Am working for uq most of this week but I'll try to have a look either Friday or early next week.

**Comment by peter-devoil** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
