### PR TITLE
Incorporated changes from Enli Wang to simulate impact of RLD and cit…

### PR DESCRIPTION
**Pull request by zur003**
…rate on P dynamics. Working on #1826

### CODE REVIEW

**Comment by zur003** [comment]
retest this please jenkins

**Comment by hol353** [comment]
This PR doesn't seem to do much. It removes add urine function and uncomments some rlv code. Is this intended?

**Comment by hol430** [comment]
retest this please jenkins

**Comment by zur003** [comment]
Closing this for now. @EnliWang - contact @hol353 for instructions on how to merge these changes into the master branch.

**Pull request closed without merging**
