### PR TITLE
Move Bootleg to Non-Validated, remove bootleg installer

### PR DESCRIPTION
**Pull request by peter-devoil**
Resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1757

@hol430 - this will not produce a bootleg installer (aka 1757.bootleg.exe), which will probably upset jenkins...

### CODE REVIEW

**Comment by hol430** [comment]
I've updated the jenkins script to ignore the bootleg installer which should hopefully get this over the line.

Will try and remember to retest this after it finishes; I could do a retest now, but it's in the middle of rebuilding its docker container (which takes a long time) so I won't interrupt.

**Comment by hol353** [comment]
@hol430 - Can you get this running green?

**Comment by hol430** [comment]
This is failing because of a problem with Bob's ftp server. I've spent a bit of time looking into this to no avail. If we're decommissioning Bob anyway, maybe it's easier to start uploading the installers somewhere else.

**Comment by hol353** [comment]
Let's put them on www.apsim.info somewhere.

**Comment by hol430** [comment]
Ok. I guess we'll have to move over existing binaries on Bob as well, and redirect the bob webpage to point to the new website.

I'll get onto this next week.

**Comment by hol353** [comment]
@hol430 Can you move the existing binaries to a folder on www.apsim.info and change bob web site to point to new location?

**Comment by hol353** [comment]
Just found out that bob is being decommissioned on 18-Oct. All existing installs / binaries need to be moved well before then.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by peter-devoil** [comment]
retest this please jenkins

**Pull request merged**
