### PR TITLE
mono-sgen vb workaround

### PR DESCRIPTION
**Pull request by peter-devoil**
Workaround in .vbproj files to address https://github.com/APSIMInitiative/APSIMClassic/issues/1655

### CODE REVIEW

**Comment by hol430** [comment]
The syntax you want is resolves #xxxx, that way the issue will be automatically closed when the pull request is merged

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by zur003** [comment]
Working on #1655

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Well, actually this doesn't resolve the original issue, but does resolve a related one.

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by hol353** [comment]
@peter-devoil Can you pull from origin and then repush to this pull request to get the branch up to date?

**Pull request closed without merging**
