### PR TITLE
Added support for two-strip intercropping, as implemented by Enli Wang.

### PR DESCRIPTION
**Pull request by zur003**
Working on #1824

### CODE REVIEW

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by zur003** [comment]
Retest this please, Jenkins

**Comment by hol353** [comment]
Are there any tests (e.g. an .apsim file somewhere) for this code?

**Comment by hol430** [comment]
retest this please jenkins

**Comment by zur003** [comment]
@hol353 - I would like to add a test before this PR is merged.

**Comment by hol353** [comment]
Ok. Go for it.

**Comment by hol353** [comment]
@zur003 Are you going to get back to this PR before you leave? If not, I'll merge it. Likewise your other PR on classic (https://github.com/APSIMInitiative/APSIMClassic/pull/1827) is red. If you're not going to it can you close it?

**Comment by zur003** [comment]
@hol353 - I won't have time to work on this. It was basically a pull request issued on behalf of @EnliWang, as he was not familiar with how pull requests are made to merge changes into master.

**Pull request closed without merging**
