### PR TITLE
Correct typo causing maize to not see P limitations.

### PR DESCRIPTION
**Pull request by zur003**
working on #1736

### CODE REVIEW

**Comment by zur003** [comment]
@hol353, @hol430 - Is the APSIMClassic build system working as intended? I had expected this pull request to fail initially, because it should have altered the outputs of the examples\MaizeP simulation. Why did it succeed?

**Comment by EnliWang** [comment]
@hol430 @zur003 - What does this mean? Eric, have you found what caused the lack of response? Can this be fixed?

**Comment by hol430** [comment]
Ok, this one's my fault, I've been making some changes to the build process. #1835 should fix the problem. Good thing someone noticed this

**Comment by zur003** [comment]
@EnliWang - Yes, I think I've found the problem. The new Maize model was ported from a Sorghum model, and was requesting a value for uptake_p_sorghum instead of uptake_p_maize - which of course didn't work.

**Comment by zur003** [comment]
@hol430 - So when #1835 is merged, should I just be able to ask Jenkins to re-test, and expect a failure? My intent is to use the failed build to generate suitably up-to-date .sum and .out files, which was a common way of working under the old build system. Is it still possible to retrieve the diffs from a failed build? If not, what is the simplest way to update output files?

**Comment by hol430** [comment]
Yeah, when #1835 is merged, you can retest this and it should run red. You can then go to [the Bob webpage](http://apsimdev.apsim.info/APSIM.Builds.Portal/Bob.aspx), and the row corresponding to this pull request *should* have a link to the .diff.zip file containing your .sum and .out files.

**Comment by zur003** [comment]
@hol353 - Do you want to revert the merge? Since the proper .out and .sum files weren't included, this may cause problems with future pull requests after #1835 is merged.

**Comment by hol353** [comment]
Ahhhhh. I misread the above comments. Ok. I'll revert.

**Comment by hol430** [comment]
Well, #1835 will be red until these diffs are accepted. So I could just add in the missing .sum and .out files into #1835, which would save you having to revert and then recreate this pull request.

**Comment by zur003** [comment]
@hol430 - Is that true even though @hol353 has reverted the change? Anyway, do whatever is needed to get builds working again.

**Comment by hol430** [comment]
Well, @hol353 hasn't reverted the change yet. The pull request which reverts it hasn't been merged.

**Comment by EnliWang** [comment]
The problem still exists. Maize growth, biomass and P uptake are at maximum. They do NOT respond to P limitations. This seems to indicate that pUptakeTotal = totalDemand, not the sum of layeredUptake.

**Comment by zur003** [comment]
What I see when I look at the Examples\MaizePSample simulation is a response on grain P uptake, but no impact at all on grain yield. That doesn't quite match your description, but also doesn't sound right.

**Pull request merged**
