### PR TITLE
Replacing the correct xml document in RunCondorJobs.cs

### LINKED ISSUE #2016: BundleAPSIM.exe does not take care of files in PlugIns
On this line: 

https://github.com/APSIMInitiative/APSIMClassic/blob/9177f64cf7eee6417929220964373970ea79a72a/Model/ApsimFile/RunCondorJob.cs#L94

'job' needs to be replaced with 'Doc.DocumentElement'.

### PR DESCRIPTION
**Pull request by BrianCollinss**
Resolves #2016

### CODE REVIEW

**Comment by BrianCollinss** [comment]
Hi @hol430, is Jenkins offline?

**Comment by hol430** [comment]
Yes. We are working on migrating it to a cloud-based build. I will see if I can temporarily revert the changes to get this pull request across the line.

**Comment by BrianCollinss** [comment]
Retest this please Jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by BrianCollinss** [comment]
@hol353, I discussed this change with @peter-devoil. I think it is good to merge.

**Pull request merged**
