### PR TITLE
working on SLN fix for DCaPS

### PR DESCRIPTION
**Pull request by jbrider**
working on #1918

### CODE REVIEW

**Comment by jbrider** [comment]
@hut104 @HamishBrownPFR @hol353  We ran into an issue using DCaPS with the wheat model in Classic where if the N concentration gets low enough, it causes a stress response for phenology.  According to the documentation wheat shouldn't have a stress response for phenology.  The wheat model avoids this issue by restricting the N concentration  and therefore never allows the N concentration levels to get that low - but the DCaPS model does get that low in very low N conditions.  
I have added an extra option that can be set in the xml config that will set the pheno stress factor to 1 without applying the multiplier so it will work as expected.  This won't affect the results from the current wheat model - or the other crops that use that calculation.  If this is acceptable, I would like to change the wheat xml to use the new option so we don't have to provide an ini file node to every wheat model to use DCaPS.

**Comment by hut104** [comment]
Jason, that is probably easier than changing parts of the model itself and will have less impact on other users.
However, this won't solve the real problem which is probably that there is not a sufficient feedback of N on photosynthesis and so N is being diluted to very low levels. You might find that you end up with unrealistic N concentrations if that continues for too long.  If your N feedback is based on different concentrations to that used in other processes, you might find things get a little unstable like that. you may need to restore balance between parameters.

________________________________

**Comment by jbrider** [comment]
Thanks @hut104 I had the same concern, but Alex's initial runs have shown it responding sensibly and in very low N situations has resulted in a better fit with the observed data. I think we were just running into an edge case with the stress mechanism when the N concentrations actually hit the minimum level that wheat was not allowing to occur. A few of the commits above were to test what other crops were doing and a couple of them would definitely be running into the issues you're referring to.  We will have a better idea what the impact is once we run it against the whole validation set.

**Comment by docalexwu** [comment]
Hi Neil and Jason,
Like to provide my comments also.
N feedback on DCaPS biomass growth is through SLN. However, the wheat model uses N concentration basis. So our solution is to calculate SLN from green leaf LAI and green leaf N.
When I compared observed vs predicted for the low N treatment in the APSIM validation data (i.e. Wheat_APS6_N000), it was apparent that the overestimated LAI was driving high DCaPS biomass growth. Because the LAI was really high, biomass increment was high, but the resulting modelled SLN was under predicted. This meant DCaPS was actually more N stressed than it needed to be.
Biomass growth in standard wheat didn't seem to respond well to the really high LAI in the Wheat_APS6_N000 simulation.
I've tested the N phenology stress fix on the entire wheat validation with DCaPS, and if anything, it improved DCaPS biomass and yield in low N simulations. If the fix has no effects on other users, I am happy with the outcomes for DCaPS.
The likely pathway to resolve this issue, exposed by a different biomass growth routine here by DCaPS, may be to examine the way N feedback on the different processes (e.g. expansion, biomass, etc.) is modelled.

Attached file shows standard vs DCaPS with/out pheno N stress fix.
[APS6_N000.pdf](https://github.com/APSIMInitiative/APSIMClassic/files/5344585/APS6_N000.pdf)

**Comment by jbrider** [comment]
@hol353 Minor changes to 3 simulations - 2 of which are lucerne sown into wheat. Not sure why it had any change, but they are small. _Warra 1988-92 Trifecta - undersown into wheat_

**Comment by hol353** [comment]
In APSIM 7.10 it is up to the model developer to get the build green. The build says:
Files that are different:

    Tests/Raphanus_raphanistrum/W400R0SWIM stress.out
    Tests/Validation/Lucerne/Warra 1988-92 Trifecta T4 - undersown into wheat.out
    Tests/Validation/Lucerne/Warra 1988-92 Trifecta T4 - undersown into wheat.sum
    Tests/Validation/Lucerne/Warra 1989-93 Trifecta T8 - undersown into wheat.out
    Tests/Validation/Lucerne/Warra 1989-93 Trifecta T8 - undersown into wheat.sum

You'll need to commit new versions of these file.

**Comment by jbrider** [comment]
oops... working on too many things at once today

**Comment by jbrider** [comment]
This is right to merge now @hol353

**Pull request merged**
