### PR TITLE
Changed CreateDiffsZip program to call new builds api.

### PR DESCRIPTION
**Pull request by hol430**
Working on #2012.

Hopefully to fix the broken builds (see: #2147).

### CODE REVIEW

**Comment by BrianCollinss** [comment]
Hey @hol430 Thanks for pushing this patch.

**Comment by BrianCollinss** [comment]
Hey @hol430 Is there going to be a fix to this issue?

**Comment by BrianCollinss** [comment]
@hol353 Hi Dean. I wonder, in the absense of Drew, might this get fixed any time soon?

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
Looks like there's a server-side problem with the builds API. You can see in the jenkins log that JOB_ID is not being set correctly because the server returns a HTML document. Someone with access to the server will need to check the logs and fix the problem.

**Comment by BrianCollinss** [comment]
Hi @hol353 . Is there going to be a fix for this? Cheers.

**Comment by hol353** [comment]
There will be but it isn't at the top of my todo list. Hopefully next week I'll get some time to look at it.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
The APSIM Classic build system is now working (hopefully). Feel free to raise a pull request.

**Pull request closed without merging**
