### PR TITLE
remove apsfarm CI2 harvesting calls

### PR DESCRIPTION
**Pull request by peter-devoil**
stops sorghum from segfaulting when an old-style variant is sent from tcl manager

### CODE REVIEW

**Comment by peter-devoil** [comment]
retest this please jenkins

Intermittent network failure?

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
Yeah there were some network-related issues in Toowoomba yesterday I think

**Comment by hol430** [comment]
retest this please jenkins

**Comment by peter-devoil** [comment]
This should allow https://github.com/APSIMInitiative/APSIMClassic/pull/1765 to proceed

**Pull request merged**
