### PR TITLE
sorghum changes for dcaps

### PR DESCRIPTION
**Pull request by jbrider**
working on #1770 

some small cleanups as well

### CODE REVIEW

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
@hol430 I think the build has broken again.

**Comment by hol430** [comment]
Ok I've aborted the build. I suspect the build server needs to be restarted but I'm not onsite today (or tomorrow probably) so this probably won't happen until next week.

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Is this ready for merging?

**Comment by jbrider** [comment]
Yes. Ready to merge.

**Pull request merged**
