### PR TITLE
Making changes in Leaf and GenericLeaf to incorporate DCaPST into Plant model

### LINKED ISSUE #1766: Making changes in Leaf and GenericLeaf to incorporate DCaPST into Plant model
Following our discusstion with @jbrider and Graeme and Alex, I made these changes in Leaf and GenericLeaf claases so users would have the option to dynamically switch between photosynthesis modules during the simulation. Two versions of DCaPST photosynthesis module have been implemented, 'dcapst' which is a stand alone module, and 'dcapstold' which is the old implementation of the module which was developed by Al (it starts with the RUE model and then switchs to DCaPST when LAI > 0.5).

### PR DESCRIPTION
**Pull request by BenAbabaei**

### CODE REVIEW

**Comment by BenAbabaei** [comment]
Jason, I made the changes as you instructed. I only kept those changes that we had discussed at the meeting. At this stage, I am mostly interested to see whether APSIM gives exaclty the same outputs as the previous merge. The 'old' version of DCapST can be discarded if not needed. It was an attempt to keep what Al had done. Most of the changes have been made in Leaf, GenericLeaf, Plant, SimplePart and PhotosynthesisModel.cpp. I hope I make some sense now. Cheers.

**Comment by jbrider** [comment]
Continuous Wheat.out should not be changed.
Being able to choose a different photosynthesis method shouldn't affect any
of the existing results.

You should also add an extra example simulation to show dcaps in use.

**Comment by hol430** [comment]
@hol353 Jenkins won't run this until you add Ben to the whitelist

**Comment by BenAbabaei** [comment]
I had reverted the example files to their original version. There should not be any difference, except the modified date, perhaps. I am working on an example for DCaPST.

**Comment by hol353** [comment]
add to whitelist Jenkins

**Comment by BenAbabaei** [comment]
@hol430 I get this error when I try to build the Plant model (with the recent changes). Could you please have a look and help me find out what is wrong?

```
  "link.exe" /OUT:"C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.dll" /MANIFEST @Plant.rsp
       Creating library C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.lib and object C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.exp
    PhotosynthesisModel.obj : error LNK2001: unresolved external symbol "public: __thiscall DCaPST::DCaPST(class ScienceAPI &,class plantInterface &)" (??0DCaPST@@QAE@AAVScienceAPI@@AAVplantInterface@@@Z)
    PhotosynthesisModel.obj : error LNK2001: unresolved external symbol "public: __thiscall DCaPSTOld::DCaPSTOld(class ScienceAPI &,class plantInterface &)" (??0DCaPSTOld@@QAE@AAVScienceAPI@@AAVplantInterface@@@Z)
    C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.dll : fatal error LNK1120: 2 unresolved externals

    make: *** [Plant.dll] Error 1120
```

**Comment by jbrider** [comment]
It can't find the dcaps dll, so it's throwing an error.

**Comment by BenAbabaei** [comment]
I am trying to put the whole DCaPST folder inside the Model folder. But SourceTree ignores the whole new folder. It also ignores all the DLLs and I don't know how to exclude DCaPST.dll.

**Comment by jbrider** [comment]
There's a folder underneath Model called Runtime that contains the dll
files that gets copied to the model directory as part of the build process.
Adding the dcaps dll to that folder should do the trick.

You can look in buildall.xml to see how it gets copied across.

**Comment by BenAbabaei** [comment]
@peter-devoil I get this error when I try to build the Plant model (with the recent changes). Could you please have a look and help me find out what is wrong? When I compile Plant with the VS (2019), I don't get this error and the DLL is built. But I do when I use the BuildAll.bat and also when compiling with Jenkins.

```
  "link.exe" /OUT:"C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.dll" /MANIFEST @Plant.rsp
       Creating library C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.lib and object C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.exp
    PhotosynthesisModel.obj : error LNK2001: unresolved external symbol "public: __thiscall DCaPST::DCaPST(class ScienceAPI &,class plantInterface &)" (??0DCaPST@@QAE@AAVScienceAPI@@AAVplantInterface@@@Z)
    PhotosynthesisModel.obj : error LNK2001: unresolved external symbol "public: __thiscall DCaPSTOld::DCaPSTOld(class ScienceAPI &,class plantInterface &)" (??0DCaPSTOld@@QAE@AAVScienceAPI@@AAVplantInterface@@@Z)
    C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.dll : fatal error LNK1120: 2 unresolved externals

    make: *** [Plant.dll] Error 1120
```

**Comment by jbrider** [comment]
@BenAbabaei It can't find the DCaPST dll.  
If you have a look at the output you will see it called Clean which cleans the model directory which removes dll files from the model directory. This is why you need to use the runtime folder that I suggested above.
I didn't tag you so maybe you didn't receive it.

**Comment by BenAbabaei** [comment]
Thanks Jason. I had received your instructsions and I followed them. I just thought that RunRime/Make file would check the Model folder and copies the DLLs if they don't already exist in that folder. I didn't consider the Clean stage. 

I will copy the DLL in that folder and try again.

I also don't know why when I try to add DCaPST folder to the Model folder and have it compiled along with other models, I get this error (it looks for a DCaPSTTest folder which doesn't exist).

```
    "C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\DCaPST\DCaPST.sln" (Build target) (1) ->
    (Build target) ->
      C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\DCaPST\DCaPST.sln.metaproj : error MSB3202: The project file "C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\DCaPST\..\DcapsTest\DcapsTest\DcapsTest.csproj" was not found. [C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\DCaPST\DCaPST.sln]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.96


    make: *** [C:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/DCaPST.dll] Error 1
```

**Comment by BenAbabaei** [comment]
I still get that error and **DaPST.dll** exists in the **Model** folder!

image


```
[Fail] Compile Plant [4sec]
    echo /NOLOGO /SUBSYSTEM:CONSOLE /DYNAMICBASE /NXCOMPAT /MACHINE:X86 /LTCG /DLL PlantComponent.obj Plant.obj PlantPart.obj PlantBiomass.obj PlantCanopy.obj PlantLibrary.obj PlantNitrogen.obj PlantP.obj Population.obj PlantStress.obj Co2Modifier.obj StageBasedInterpolationFunction.obj Environment.obj Fixation.obj Stem.obj CompositePart.obj SimplePart.obj PlantSpatial.obj Pool.obj CompositePool.obj CompositeDelta.obj Delta.obj Biomass.obj ThingFactory.obj Parts.obj StdPlant.obj Utility/PlantUtility.obj Utility/Data.obj Utility/ExternalFunction.obj Utility/InterpolationFunction.obj Utility/LookupFunction.obj Utility/Science.obj Utility/Date.obj Utility/Observers.obj Utility/Output.obj Utility/OutputVariable.obj Storage/StoragePart.obj ReproductivePart.obj Reproductive/PodPart.obj Reproductive/PodPartFN.obj Reproductive/FloretPart.obj Reproductive/MealPart.obj Reproductive/OilPart.obj Reproductive/GrainPart.obj Reproductive/GrainPartHI.obj Reproductive/GrainPartGN.obj Reproductive/GrainPartFN.obj Reproductive/FruitCohort.obj Reproductive/FruitCohortFN.obj Reproductive/PlantFruitCohorting.obj Root/RootBase.obj Root/RootPart.obj Root/Soil.obj Root/NoRoot.obj Root/MultiRoot.obj Root/RootGrowthOption1.obj Root/RootGrowthOption2.obj Leaf/Leaf.obj Leaf/Culm.obj Leaf/IndividualLeaf.obj Leaf/GenericLeaf.obj Leaf/CohortingLeaf.obj Arbitrators/Arbitrator.obj Arbitrators/GenericArbitrator.obj Arbitrators/GenericArbitratorXY.obj Arbitrators/WholePlantGenericArbitratorXY.obj Arbitrators/WholePlantSeasonalArbitrator.obj Arbitrators/WholePlantSeasonalPpArbitrator.obj Phenology/Phenology.obj Phenology/Phase.obj Phenology/CompositePhase.obj Phenology/FixedPhase.obj Phenology/InductivePhase.obj Phenology/VernalPhase.obj Phenology/PhotoPhase.obj Phenology/EmergentPhase.obj Phenology/LeafAppPhase.obj Phenology/SowingPhase.obj Phenology/WaitingPhase.obj Phenology/CWEmergentPhase.obj Phenology/CWVernalPhase.obj Phenology/CWInductivePhase.obj Phenology/CWSowingPhase.obj Phenology/CWFixedPhase.obj Phenology/Zadok.obj Photosynthesis/PhotosynthesisModel.obj Photosynthesis/RUEModel.obj Photosynthesis/RUEWholePlantModel.obj Photosynthesis/Weather.obj Photosynthesis/SUCROSModel.obj kernel32.lib user32.lib advapi32.lib shell32.lib uuid.lib C:\Users\uqbababa\UQ\07_Repository\ApsimClassic/Model/ComponentInterface/EntryPoints.obj /DEF:Plant.def /LIBPATH:C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model /LIBPATH:C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\..\BuildLibraries\libxml2-2.9.4.win32\lib /LIBPATH:C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\..\BuildLibraries\libiconv-1.11.1.win32\lib /LIBPATH:C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\..\BuildLibraries\cppunit-1.13.2\lib  General.lib ComponentInterface.lib ApsimShared.lib libxml2.lib > Plant.rsp
    "link.exe" /OUT:"C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.dll" /MANIFEST @Plant.rsp
       Creating library C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.lib and object C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.exp
    PhotosynthesisModel.obj : error LNK2001: unresolved external symbol "public: __thiscall DCaPST::DCaPST(class ScienceAPI &,class plantInterface &)" (??0DCaPST@@QAE@AAVScienceAPI@@AAVplantInterface@@@Z)
    PhotosynthesisModel.obj : error LNK2001: unresolved external symbol "public: __thiscall DCaPSTOld::DCaPSTOld(class ScienceAPI &,class plantInterface &)" (??0DCaPSTOld@@QAE@AAVScienceAPI@@AAVplantInterface@@@Z)
    C:\Users\uqbababa\UQ\07_Repository\ApsimClassic\Model\Plant.dll : fatal error LNK1120: 2 unresolved externals
```

**Comment by BenAbabaei** [comment]
I managed to make the code build and test all the files, except at the end I got these errors related to **Diff Zip**, **Bootleg** and others. To solve my problem, I needed to add the new cpp files to the **Make** file under the **Plant** folder.

```
[Fail] Create Diff Zip [36sec]

    Directory = C:/APSIM

    Creating diff file: C:\APSIM\1767.diffs.zip

    System.Net.WebException: The remote server returned an error: (404) Not Found.

       at System.Net.HttpWebRequest.GetResponse()

       at Utils.REST.CallService[T](String url) in C:\APSIM\Model\JobScheduler\IfCleanDoCommit\RESTUtility.cs:line 34

       at Program.ReportNumDiffs(String ApsimDirectoryName, List`1 ModifiedFiles, String PatchFileName, String outZip) in C:\APSIM\Model\JobScheduler\CreateDiffZip\CreateDiffZip.cs:line 186

       at Program.Go(String[] args) in C:\APSIM\Model\JobScheduler\CreateDiffZip\CreateDiffZip.cs:line 121

       at Program.Main(String[] args) in C:\APSIM\Model\JobScheduler\CreateDiffZip\CreateDiffZip.cs:line 24

[Pass] Create SFX Binaries [45sec]

[Fail] Create Release MSI [110sec]

    

    

    Verifying: ApsimSetup\1767.ApsimSetup.exe

    

    

    Number of files successfully Verified: 0

    

    Number of warnings: 0

    

    Number of errors: 1

    

    

    

    SignTool Error: No certificates were found that met all the given criteria.

    SignTool Error: No signature found.

    

[Fail] Create Bootleg MSI [110sec]

    

    

    Verifying: Bootleg\1767.Bootleg.exe

    

    

    Number of files successfully Verified: 0

    

    Number of warnings: 0

    

    Number of errors: 1

    

    

    

    SignTool Error: No certificates were found that met all the given criteria.

    SignTool Error: No signature found.

    

[Fail] Target: JenkinsRun [118sec]



[Fail] Project: JenkinsRun [1857sec]



Uploading 1767.xml...

Uploading 1767.diffs.zip...

Flagging build as failed...

script returned exit code 1
```

**Comment by jbrider** [comment]
There is an issue with the final part of the build at the moment.
Hopefully it will be fixed soon.

**Comment by BenAbabaei** [comment]
retest this please jenkins

**Comment by BenAbabaei** [comment]
I ran APSIM with and without my changes and the differences are usually of a very small order. I am not even sure why they exist. Any suggestion?

image

image

**Pull request closed without merging**
